# Generated by Django 4.2 on 2023-04-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email_address')),
                ('password', models.CharField(max_length=255)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
    ]
