# Generated by Django 4.2 on 2023-04-21 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_proxyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyuser',
            name='iat',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 12, 8, 34, 836497)),
            preserve_default=False,
        ),
    ]
