# Generated by Django 4.2 on 2023-04-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_proxyuser_iat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxyuser',
            name='iat',
        ),
        migrations.AddField(
            model_name='proxyuser',
            name='otp_attempt',
            field=models.SmallIntegerField(default=3),
        ),
    ]
