# Generated by Django 4.2 on 2023-04-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_proxyuser_iat_proxyuser_otp_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyuser',
            name='otp',
            field=models.SmallIntegerField(),
        ),
    ]
