# Generated by Django 4.2 on 2023-04-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_proxyuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyuser',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
